### ISSUE TITLE
Feedback: HashTable

### ISSUE THREAD

**Issue by anselb** [diop/believable-african-proverbs#1]
- It seems most of your tests would pass if you fixed the typo on line 108. There is also a bug in your `bucket.find` line in the `set method`.
- Try to analyze the runtime of each method. I think you should be able to fill some in based on what you learned in class.
- I also recommend dispersing the comments you have at the top of each method next to where that comment actually happens in code.

**Comment by diop** [comment]
Thank you @anselb. I will take the feedback into consideration. I might need your help later today if you are free.

**Comment by diop** [comment]
Thank you for the tips @anselb All hashtable tests are now passing.
